disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - line_length
  - identifier_name
  - empty_enum_arguments
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - vendor
