language: objective-c
osx_image: xcode8.3
xcode_workspace: FlyveMDMInventoryAgent.xcworkspace
xcode_scheme: FlyveMDMInventoryAgent
podfile: Podfile
before_install:
- chmod a+x scripts/add-key.sh
- chmod a+x scripts/run-build.sh
- chmod a+x scripts/remove-key.sh
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
before_script:
- "./scripts/add-key.sh"
- echo FASTLANE_PASSWORD=$FASTLANE_PASSWORD >> .env
script:
- xcodebuild clean build -workspace FlyveMDMInventoryAgent.xcworkspace -scheme FlyveMDMInventoryAgent
- "./scripts/run-build.sh"
after_script:
- "./scripts/remove-key.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="FlyveMDMInventoryAgent"
  - PROFILE_UUID=XC_iOS_orgflyveinventoryagentexample
  - KEYCHAIN_NAME="ios-app.keychain"
  - SCRIPT_PATH=./scripts
  - CERTIFICATES_PATH=./scripts/cert
  - PROFILE_PATH=./scripts/profile
  - secure: Q2e8oFTqye1P4MQIDGXkKpKJS4Am9gykEkNiAukUfakiyQLbNfhKjmKY6XMUi++t9oOIy/HDMYRh2EUMz9jQfLBdqTvYx5zZaIcKrpSx+K7wNPR/MtsOGoXkKJJsiM90y4uXhMI8R3SGs19tf0ZCqziNlAtagE5LG4XxKalY28iCZO5s1k/7ZICrhD5Vp38ntUxSCcZvDdYg51WuuhcNan8hURx4rYSoHhvIWVundTZB0zpPrdDXAwcZES4/IzCoC4Lyx9X0HtBN1Gxc8d6WKqUqZILHdkIDELzeaV4ZTy2EQv1+xAozY99JpNRRfouKjcWgN9LsvXVz+6TM9+2rpTvAqlQunPslC60y/jEl12xP+vYAxF3Qs2/POlDy3e+ZX9wLgKKxiOOBnthV9X00UkiK8guiKu6VRY/nt1fUzfdn39bNOjDavx2yRrgQps5hSboMYYoKhgfqtfeKPkRipRWBmlNwmDEV64gzXT+lS6p/BmunubXJPHrHkBIXDnQVyXdMOcS7EOlWcrz4pCoRejLPoDA7H3qJb250aYkUt8QuGQ8TzQjOWS89GeRHPL9bNhSD5PxY8oxG+xKxbjQnxlyzvWeQsHtgKZBsQWpEtSdo4o/CXkuOM0s1UKsOoxuRjb1/TN7jhjvNRPTuidXbK0MuEXLg8CYVGJ9cGV2wEwQ=
  - secure: TLAFnrbZPgzByGG7Mh0a4M8vkP0cwGozE8kvqb6s3zUouJQqRf4Yw+DnuT7o9qntmIanIfekwRDN64A++I7QQoeFOw+HsYbGrwB85C2BHOgrSrnvH6yUKCKJ0bxlagLFPylA3yc/Iai6SVqvLrQRTNofSkQEAL5zg8w8BdPUBXaG077bUiCQJmkGoVQZgIW4tZeeNnl8BCR299UnA2o6bIHXN3seTEO+nPL5gboPWzFiv6EFQ7O1kurk+/FqxV4lq+oWXM8c4//G+XgUXWvvSInGiHkQVQxdYcvI3LFqQcWYPwyxS4u64A+rqnRVP10ZeACkqYTCs6emMvkldikA+m58z3t7UA9IYUVRAKdKxQOVH5OtG6jHwZneoD3nwcmCPQvs19lR/lEvmDFdGr1IggAyUMp3c8v4f4RiFGLQoGPxFW1FoXDFWk5D+5D2KjbM2wjQVXbcvYt1wcFJHzNVRNgAy1HJqzB9GHphcmffBrxchBxoxQOZlhv4fPHyD9yue70UEqMJeKp6f0uBHue+7KYQiSF3IQ2HPDHJGZRwYIBvHT1Kw8rXG9ieadqJ+hNSIAxGAw6i+Z92O4IaiGkM6UIcKm2UNi8hl27Q0z9pTSXAUOAz+bRghNHOU0Sm+Vax9ZCXgtIC4BkQnBoDILoDuoM8dPXePavCOJ0swu+DnGE=
