language: objective-c
osx_image: xcode8.3
xcode_workspace: FusionInventory.xcworkspace
xcode_scheme: FusionInventory

script:
- xcodebuild clean build -workspace FusionInventory.xcworkspace -scheme FusionInventory
