version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Configure Ruby dependencies
          command: source ./ci/scripts/install_ruby.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
