version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: run build
          command: source ./ci/scripts/test.sh
          environment:
            APPNAME: FlyveMDMInventoryAgent

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
